name: CI

on: [push, pull_request]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.14.1-ocaml-4.14.1-flambda' 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run autosubst
        uses: coq-community/docker-coq-action@v1
        with:
          custom_image: ${{ matrix.image }}
          opam_file: ${{ matrix.opam_file }}
          before_script: |
            startGroup "fix permission issue"
              sudo chown -R coq:coq .
            endGroup
          script: |
            startGroup "install autosubst"
              opam pin -y coq-autosubst-ocaml "https://github.com/uds-psl/autosubst-ocaml.git#coq-8.14"
            endGroup
          after_script: |
            startGroup "Run benchmarks"
              ls *.sig | xargs -i{} basename {} .sig | xargs -i{} autosubst {}.sig -o {}.v -f -no-static -allfv -fext
              ls *.sig | xargs -i{} basename {} .sig | xargs -i{} autosubst {}.sig -o {}.v -f -no-static -allfv -fext -s coq
            endGroup
      - uses: actions/upload-artifact@v4
        with:
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: "*.v"

